homepage_settings:
  countdown:
    show: false
    timezone: Europe/London
    deadline: 2025-01-31 12:00
  modal:
    show: false
    delay: 5000
  testimonials:
    show: false
    title: "Testimonials"
  gallery:
    show: false
    title: "Code BEAM Lite London 2025"