homepage_settings:
  countdown:
    show: true
    timezone: Europe/London
    deadline: 2025-01-31 09:00
  modal:
    show: false
    delay: 5000
  testimonials:
    show: false
    title: "Testimonials"
  gallery:
    show: true
    title: "Code BEAMs"