---
trainings:
- training: _trainings/tdd-and-restful-phoenix.md
  start: 2025-01-28 09:00:00
  end: 2025-01-30 17:00:00
  timezone: GMT
- training: _trainings/architecting-systems-for-scalability-and-reliability.md
  start: 2025-01-30 09:00:00
  end: 2025-01-30 17:00:00
  timezone: GMT


# Below values need to be written down manually according to 
# event specific timezone and dates
# timezone - timezone of the event e.g. EST
# start - start date and time of the event !!! time in 24-hour format !!!
# end - end date and time of the event !!! time in 24-hour format !!!